import { useMemo } from 'react';
import { create } from 'zustand';

/**
 * 极简 i18n。
 *
 * 只支持中文 / 英文两套，而且**直接用中文原文当 key**：
 *   - 词典只维护 zh → en 一张表；
 *   - 漏翻的条目会原样回退成中文，不会在界面上出现 `model.settings.title`
 *     这种 key。所以可以放心地一条一条补，不用一次性全改完。
 *   - 需要变量时用 `{name}` 占位。
 *
 * 组件里用 `useT()`（语言一变就重渲染）；非组件环境（store / notification）
 * 直接用导出的 `t()`。
 */

export type Lang = 'zh' | 'en';

const STORAGE_KEY = 'treeai-lang';

/** zh → en。key 是界面上的中文原文。 */
const en: Record<string, string> = {
  // ── 通用 ──────────────────────────────────────────────
  设置: 'Settings',
  关闭: 'Close',
  取消: 'Cancel',
  保存: 'Save',
  重命名: 'Rename',
  删除: 'Delete',
  添加: 'Add',
  模型: 'Model',
  温度: 'Temperature',
  最大令牌数: 'Max tokens',
  重试: 'Retry',
  默认: 'Default',
  全部: 'All',
  未分类: 'Uncategorized',
  创建: 'Created',
  更新: 'Updated',
  复制到剪贴板: 'Copy to clipboard',
  模型设置: 'Model settings',
  删除节点: 'Delete node',
  添加子节点: 'Add child node',
  '先让这个节点得到回答，再从这里追问': 'Get an answer first, then branch from here',
  '重新生成回复（另起一个新分支，保留当前回答）':
    'Regenerate (new sibling branch, keeps this answer)',

  // ── App ───────────────────────────────────────────────
  '加载中...': 'Loading...',
  '欢迎使用 Tree AI Plus': 'Welcome to Tree AI Plus',
  '创建一个新会话，开始与 AI 进行树状结构的对话。':
    'Create a session and start a tree-structured conversation with AI.',
  设置模型: 'Set up a model',
  创建新会话: 'New session',

  // ── Sidebar ───────────────────────────────────────────
  会话名称已更新: 'Session renamed',
  会话名称不能为空: 'Session name cannot be empty',
  会话已删除: 'Session deleted',
  '已创建文件夹「{name}」': 'Folder "{name}" created',
  文件夹已重命名: 'Folder renamed',
  '删除文件夹「{name}」？\n里面的会话会移到「未分类」，不会被删除。':
    'Delete folder "{name}"?\nIts sessions will move to "Uncategorized" — they will not be deleted.',
  '文件夹已删除，会话已移到「未分类」': 'Folder deleted — its sessions moved to "Uncategorized"',
  '搜索标题或内容...': 'Search titles or content...',
  清除搜索: 'Clear search',
  显示全部会话: 'Show all sessions',
  只看收藏: 'Starred only',
  删除文件夹: 'Delete folder',
  文件夹名: 'Folder name',
  新建文件夹: 'New folder',
  '新建文件夹…': 'New folder…',
  没有匹配的会话: 'No matching sessions',
  还没有收藏的会话: 'No starred sessions yet',
  这个文件夹还是空的: 'This folder is empty',
  暂无会话: 'No sessions yet',
  取消收藏: 'Unstar',
  收藏会话: 'Star session',
  移动到文件夹: 'Move to folder',
  移动到: 'Move to',
  '拖动会话到文件夹即可归类': 'Drag a session onto a folder to file it',
  切换到日间模式: 'Switch to light mode',
  切换到夜间模式: 'Switch to dark mode',
  新建会话: 'New session',

  // ── ChatNode ──────────────────────────────────────────
  内容已复制到剪贴板: 'Copied to clipboard',
  对话节点: 'Chat node',
  节点已删除: 'Node deleted',
  消息已保存: 'Message saved',
  '在此输入您的消息...': 'Type your message...',
  '点击添加消息...': 'Click to add message...',
  'AI 正在思考...': 'AI is thinking...',
  '思考过程 · {n} 字': 'Reasoning · {n} chars',
  '思考中…': 'Thinking…',
  '请求失败，可重试': 'Request failed — you can retry',
  AI回复将显示在这里: 'The AI reply will appear here',
  '{n} 字': '{n} chars',
  '输出速度（含首字延迟）': 'Output speed (incl. first-token latency)',
  '命中缓存 {hit} tok，未命中 {miss} tok': 'cache hit {hit} tok, miss {miss} tok',
  '缓存 {n}%': 'Cache {n}%',
  '输入 token · 输出 token': 'input tokens · output tokens',
  '思考消耗的 token': 'Reasoning tokens',
  '思考 {n}': 'Thinking {n}',

  // ── SystemNode ────────────────────────────────────────
  系统提示词: 'System prompt',
  '在此输入系统提示词...': 'Type the system prompt here...',
  '点击添加系统提示词...': 'Click to add a system prompt...',

  // ── ChatFlow ──────────────────────────────────────────
  '该节点引用的模型不存在，请在节点设置里重新选一个模型':
    "This node's model no longer exists — pick another one in the node settings",
  '已创建新分支，正在重新生成…': 'New branch created, regenerating…',
  '已切换到 {name}，系统提示词一并更新': 'Switched to {name}; system prompt updated too',
  '已切换到模型: {name}': 'Switched to model: {name}',
  导出成功: 'Exported',
  '导出失败: {msg}': 'Export failed: {msg}',
  会话已导出: 'Session exported',
  会话统计: 'Session stats',
  '导出当前会话（JSON）': 'Export this session (JSON)',
  导出思维导图: 'Export mind map',
  重新排布节点: 'Re-layout nodes',

  // ── SessionStats ──────────────────────────────────────
  节点: 'Nodes',
  提问: 'Questions',
  回答: 'Answers',
  分支: 'Branches',
  分支点: 'Branch points',
  '同一父节点下第 2 个及以后的孩子': '2nd and later children of the same parent',
  '有 2 个以上孩子的节点数': 'Nodes with 2+ children',
  '↓ 输入 token': '↓ Input tokens',
  '发给模型的 token（提示词）': 'Tokens sent to the model (prompt)',
  '↑ 输出 token': '↑ Output tokens',
  '模型生成的 token': 'Tokens generated by the model',
  '思考 token': 'Reasoning tokens',
  缓存命中: 'Cache hit',
  计费次数: 'Billed calls',
  '有 token 用量的回答数': 'Answers with token usage',
  回答字数: 'Answer characters',

  // ── Settings ──────────────────────────────────────────
  数据: 'Data',
  外观: 'Appearance',
  关于: 'About',
  语言: 'Language',
  主题: 'Theme',
  浅色: 'Light',
  明亮的白色界面: 'Bright, light interface',
  深色: 'Dark',
  夜间护眼的暗色界面: 'Dark, easy-on-the-eyes interface',
  '选择界面配色。这个偏好保存在本地，下次打开仍然生效。':
    'Choose the interface colors. This preference is saved locally and kept next time.',
  '选择界面语言。这个偏好保存在本地，下次打开仍然生效。':
    'Choose the interface language. This preference is saved locally and kept next time.',

  // ── ModelsPanel ───────────────────────────────────────
  '确定要删除这个模型吗？': 'Delete this model?',
  模型列表: 'Models',
  暂无配置模型: 'No models configured',
  模型名称: 'Name',
  'API 地址': 'API base URL',
  'API 密钥': 'API key',
  '模型标识 (例如: gpt-4)': 'Model ID (e.g. gpt-4)',
  '思考强度 (reasoning_effort)': 'Reasoning effort (reasoning_effort)',
  'DeepSeek V4 起 thinking 默认开启且 effort=high。聊天场景建议 low：思考量小、响应快、输出 token 便宜。':
    'Since DeepSeek V4, thinking is on by default with effort=high. For chat, low is recommended: less thinking, faster replies, cheaper output tokens.',
  默认系统提示词: 'Default system prompt',
  '（可留空）': '(optional)',
  '留空则不发送 system 消息 —— 这是合法请求，大多数模型不带系统提示词也能正常对话':
    'If empty, no system message is sent — that is a valid request; most models chat fine without a system prompt.',
  默认温度: 'Default temperature',
  默认最大令牌数: 'Default max tokens',
  保存模型: 'Save model',
  模型配置: 'Model settings',
  '从左侧列表选择一个模型进行编辑，或创建一个新模型。':
    'Select a model on the left to edit, or create a new one.',
  添加新模型: 'Add model',
  '拖动调整顺序，': 'Drag to reorder. ',
  '第一项就是默认模型': 'the first item is the default model',
  '，新建对话会自动使用它。': ', used automatically for new conversations.',

  // ── DataPanel ─────────────────────────────────────────
  还没有会话可以导出: 'No sessions to export yet',
  '已导出 {n} 个会话': 'Exported {n} sessions',
  读取文件失败: 'Failed to read the file',
  '导入失败：{msg}': 'Import failed: {msg}',
  '没有新增内容：这 {n} 个会话都已经存在了': 'Nothing new: these {n} sessions already exist',
  文件里没有可导入的内容: 'Nothing to import in this file',
  '新增 {n} 个会话': '{n} sessions added',
  '跳过 {n} 个已存在的': '{n} existing skipped',
  '新建 {n} 个文件夹': '{n} folders created',
  '导入 {n} 个模型配置（需重填 API Key）': '{n} model configs imported (re-enter API keys)',
  '导入完成：{parts}': 'Import complete: {parts}',
  当前数据: 'Current data',
  '所有数据都只存在这台浏览器的 IndexedDB 里，不会上传到任何服务器。':
    "All data lives only in this browser's IndexedDB — nothing is uploaded to any server.",
  个会话: 'sessions',
  个文件夹: 'folders',
  个模型配置: 'model configs',
  备份: 'Backup',
  '导出全部会话、文件夹与模型配置为一个 JSON 文件。换电脑、换浏览器时，拿它搬数据就行。':
    'Export all sessions, folders, and model configs into one JSON file. Use it to move your data across computers or browsers.',
  导出全部会话: 'Export all sessions',
  恢复: 'Restore',
  '选一个备份文件就能恢复。': 'Pick a backup file to restore. ',
  '新的全部会导入，已经有的自动跳过': 'Everything new is imported; existing items are skipped',
  ' ——\n同一份文件重复导入、或者在几台设备之间来回互导，都不会重复、不会覆盖、不会越导越乱，放心导就行。':
    ' —\nImporting the same file twice, or bouncing between devices, never duplicates, overwrites, or makes a mess.',
  '出于安全考虑，备份文件里': 'For security, backup files ',
  '不包含 API Key': 'do not contain API keys',
  '，导入后需要重新填一次。': '; re-enter them after import.',
  导入备份: 'Import backup',
  '只想导出某一个会话？在画布右上角点「导出当前会话」即可。它和这里导出的是同一种文件，\n可以直接互相导入。':
    'Want just one session? Click "Export this session" at the top-right of the canvas. It is the same file format and the two can import each other.',

  // ── AboutPanel ────────────────────────────────────────
  它能做什么: 'What it does',
  数据与隐私: 'Data & privacy',
  项目链接: 'Links',
  本分支源码: "This fork's source",
  上游项目: 'Upstream project',
  '一个把线性对话变成画布的本地优先工作台。':
    'A local-first workbench that turns linear chat into a canvas.',
  '每个回答都可以继续分叉，把「换一种问法」「换一个模型」变成可以对照的树。':
    'Every answer can branch further, turning "ask differently" and "try another model" into trees you can compare side by side.',
  '树状分支对话：同一个问题可以有很多种回答，并排比较':
    'Tree branching: one question can have many answers, compared side by side',
  '任意 OpenAI 兼容服务：DeepSeek / OpenAI / Ollama / 各种兼容层':
    'Any OpenAI-compatible service: DeepSeek / OpenAI / Ollama / compatibility layers',
  '推理模型友好：思考链实时显示、可回看，推理强度可配':
    'Reasoning-friendly: live chain-of-thought, replayable, configurable effort',
  '每条回答的 token 用量与缓存命中率统计':
    'Per-answer token usage and cache-hit stats',
  '本地优先：数据只存在浏览器的 IndexedDB，不上传任何服务器':
    "Local-first: data lives only in the browser's IndexedDB, never uploaded",
  '完全离线运行：零第三方 CDN 请求，可部署到内网':
    'Fully offline: zero third-party CDN requests, deployable on an intranet',
  'JSON 备份与恢复，单个会话也能单独导出':
    'JSON backup and restore, plus per-session export',
  '会话与模型配置都保存在这台浏览器里，卸载或清理浏览器数据会一并删除，':
    'Sessions and model configs are saved in this browser; uninstalling or clearing browser data deletes them too. ',
  '请定期用「设置 → 数据」导出备份。API Key 绝不会进入备份文件。':
    'Back up regularly via Settings → Data. API keys never enter backup files.',
  'Tree AI Plus 是': 'Tree AI Plus is an enhanced fork of ',
  '的增强分支。': '.',
  '如果你觉得有用，欢迎给两个仓库都点个 Star。':
    'If you find it useful, a star on both repos is appreciated.',
  用: 'Built with ',
  构建: '',

  // ── reasoningEffort ───────────────────────────────────
  '默认（不发送该参数）': 'Default (do not send the parameter)',
  '关闭思考 (none)': 'Off (none)',
  '低 (low)': 'Low (low)',
  '高 (high)': 'High (high)',
  '最高 (max)': 'Max (max)',

  // ── sessionTransfer ───────────────────────────────────
  '不是有效的 JSON 文件': 'Not a valid JSON file',
  '文件内容不是一个对象': 'The file content is not an object',
  '这不是 Tree AI Plus 导出的备份文件': 'This is not a backup exported by Tree AI Plus',
  '文件缺少版本号': 'The file has no version number',
  '文件版本 v{v} 比当前程序新（最高支持 v{max}），请先升级':
    'File version v{v} is newer than this app (max v{max}); please update first',
  '文件里没有 sessions 数组': 'The file has no sessions array',
  '文件里没有有效的会话': 'The file has no valid sessions',

  // ── modelStore ────────────────────────────────────────
  模型创建成功: 'Model created',
  '模型创建失败: {msg}': 'Failed to create model: {msg}',
  模型更新成功: 'Model updated',
  '模型更新失败：{msg}': 'Failed to update model: {msg}',
  模型已删除: 'Model deleted',
  '模型删除失败: {msg}': 'Failed to delete model: {msg}',
  '调整顺序失败: {msg}': 'Failed to reorder: {msg}',
};

function interpolate(s: string, vars?: Record<string, string | number>): string {
  if (!vars) return s;
  return s.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
}

function readStoredLang(): Lang | null {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    return saved === 'zh' || saved === 'en' ? saved : null;
  } catch {
    return null;
  }
}

function detectLang(): Lang {
  return typeof navigator !== 'undefined' && navigator.language?.toLowerCase().startsWith('zh')
    ? 'zh'
    : 'en';
}

export function applyLang(lang: Lang): void {
  document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
}

const initialLang: Lang = readStoredLang() ?? detectLang();

interface LangState {
  lang: Lang;
  setLang: (lang: Lang) => void;
}

export const useLangStore = create<LangState>((set) => ({
  lang: initialLang,
  setLang: (lang) => {
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch {
      // 写不进去也无所谓，当前会话仍然生效
    }
    applyLang(lang);
    set({ lang });
  },
}));

/** 当前语言下的翻译（非组件环境用）。 */
export function t(zh: string, vars?: Record<string, string | number>): string {
  const { lang } = useLangStore.getState();
  return interpolate(lang === 'zh' ? zh : en[zh] ?? zh, vars);
}

/** 组件内用：语言切换会自动重渲染。 */
export function useT(): (zh: string, vars?: Record<string, string | number>) => string {
  const lang = useLangStore((s) => s.lang);
  return useMemo(
    () => (zh: string, vars?: Record<string, string | number>) =>
      interpolate(lang === 'zh' ? zh : en[zh] ?? zh, vars),
    [lang],
  );
}

applyLang(initialLang);
